### ISSUE TITLE
Question: how is this repo used?

### ISSUE THREAD

**Issue by Leedehai** [TypedProject/vuepress-theme-tsed#1]
Can I just copy paste this whole repo into `.vuepress/theme` and make changes to my `config.js` accordingly, and it's done?
And is there an example/boilerplate for the `config.js`'s `themeConfig`?
I really want a **drop-in** replacement for the default theme. Thanks! This is a very good theme.

**Comment by Romakita** [comment]
@Leedehai Honestly I don't know ^^ I use this themes for tsed.fr for the documentation.
You can take as example this repository https://github.com/Romakita/ts-express-decorators/tree/master/docs

Add `theme: 'tsed'` or fork the repository and create your own npm package ;)

Other point, this theme use Sass instead of stylus. Sass isn't officially supported by VuePress. So the all documentation/feature/customization available for Stylus doesn't works this theme ^^.

See you,
Romain
